[project]
name = "fundamental-ap-jb2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yue Hao", email = "haoyue@msu.edu" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter-book>=2.1.6",
]

[project.scripts]
fundamental-ap-jb2 = "fundamental_ap_jb2:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
